name: Update Hexo Website

# 触发条件
on:
  workflow_dispatch:

jobs:
  Update-Hexo-Website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # sparse-checkout: .git
        ref: main
        path: main

    - name: Checkout Hexo data
      uses: actions/checkout@v4
      with:
        ref: hexo_data
        path: hexo_data

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 22.x

    - name: Install Hexo and deploy
      run: |
        sudo npm install hexo-cli -g
        mkdir hexo && cd hexo
        hexo init
        npm install
        npm install hexo-theme-next
        rm -rf source && mv ../hexo_data/* .
        hexo deploy

    - name: Push changes to GitHub
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         cd main
         rm -rf *
         cp -R ../hexo/public/* .
         git add .
         git commit -m "Update Hexo Website on $(date '+%Y-%m-%d %H:%M:%S')"
         git push
